FROM node:18-bullseye

RUN apt-get update && apt-get install -y git python3 make g++

WORKDIR /app
COPY package*.json ./
RUN npm install

COPY . .

RUN npm install -g pkg
RUN pkg stany.js --targets node18-linux-x64 --output core.bin --options expose-gc