databases:
  - name: stanytz
    plan: free
    databaseName: stanytz
    user: stanytz

services:
  - type: web
    name: mia-khalifa
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MODE
        value: public
      - key: TIME_ZONE
        value: Africa/Nairobi
      - key: AUTO_LIKE_STATUS
        value: "true"
      - key: AUTO_READ_STATUS
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: stanytz-db
          property: connectionString
